name: "dnsx Action"
description: "dnsx is a fast and multi-purpose DNS toolkit allow to run multiple DNS queries."
branding:
  icon: "activity"
  color: "blue"

inputs:
  list:
    description: "List of hosts to perform DNS resolution"
    required: true
    default: ""

  output:
    description: "File to save output result"
    required: false
    default: "dnsx.log"

  flags:
    description: "Additional dnsx CLI flags to use"
    required: false

  json:
    description: "Format to save of output file"
    required: false
    default: false

  resolver:
    description: "List of custom resolvers to use"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - run: |
        [ ! -x /home/runner/go/bin/dnsx ] && GO111MODULE=on go get -v github.com/projectdiscovery/dnsx/cmd/dnsx@v1.0.4
        [ ! -z ${{ inputs.list }} ] && echo "list=-l ${{ inputs.list}}" >> $GITHUB_ENV
        [ ! -z ${{ inputs.output }} ] && echo "output=-o ${{ inputs.output}}" >> $GITHUB_ENV || echo "output=-o dnsx.log" >> $GITHUB_ENV
        [ ! -z "${{ inputs.flags }}" ] && echo "flags=${{ inputs.flags }}" >> $GITHUB_ENV
        [ ! -z ${{ inputs.resolver }} ] && echo "resolver=-r ${{ inputs.resolver}}" >> $GITHUB_ENV
        ${{ inputs.json }} && echo "json=-json" >> $GITHUB_ENV
        echo "/home/runner/go/bin/" >> $GITHUB_PATH
      shell: bash

    - run: |
        dnsx \
          ${{ env.list }} \
          ${{ env.output }} \
          ${{ env.json }} \
          ${{ env.resolver }} \
          ${{ env.flags }}
      shell: bash
