name: 💥 dnsx - DNS Resolver

on:
    schedule:
      - cron: '0 0 * * *'
    workflow_dispatch:
      inputs: 
        name:
          description: "List of hosts to perform DNS resolution"
          default: ''
          required: true
jobs:
  dnsx:
    runs-on: ubuntu-latest
    steps:
      - name: checkdsnx
        run: |
              [ ! -x /home/runner/go/bin/dnsx ] && go install -v github.com/projectdiscovery/dnsx/cmd/dnsx@latest
              [ ! -z ${{ inputs.list }} ] && echo "list=-l ${{ inputs.list}}" >> $GITHUB_ENV
              [ ! -z ${{ inputs.output }} ] && echo "output=-o ${{ inputs.output}}" >> $GITHUB_ENV || echo "output=-o dnsx.log" >> $GITHUB_ENV
              [ ! -z "${{ inputs.flags }}" ] && echo "flags=${{ inputs.flags }}" >> $GITHUB_ENV
              [ ! -z ${{ inputs.resolver }} ] && echo "resolver=-r ${{ inputs.resolver}}" >> $GITHUB_ENV
              ${{ inputs.json }} && echo "json=-json" >> $GITHUB_ENV
              echo "/home/runner/go/bin/" >> $GITHUB_PATH
              
