name: 💥 dnsx - DNS Resolver

on:
    schedule:
      - cron: '0 0 * * *'
    workflow_dispatch:
      inputs: 
        list:
          description: "List of hosts to perform DNS resolution"
          default: 'host.txt'
          required: true
          
        output:
            description: "File to save output result"
            required: false
            default: "dnsx.log"
        flags:
            description: "Additional dnsx CLI flags to use"
            required: false
        
        json:
            description: "Format to save of output file"
            required: false
            default: false
        
        resolver:
            description: "List of custom resolvers to use"
            required: false
            default: ""
            
            
jobs:
  dnsx:
    runs-on: ubuntu-latest
    steps:
      - name: check_env_dnsx
        run: |
            # whoami
            # which go 
            # echo "list=-l ${{ inputs.list}}"
            # echo "list=-l ${{ inputs.list}}" >> $GITHUB_ENV
            # echo $GITHUB_ENV
            [ ! -x /home/runner/go/bin/dnsx ] && go install -v github.com/projectdiscovery/dnsx/cmd/dnsx@latest
            [ ! -z ${{ inputs.list }} ] && echo "list=-l ${{ inputs.list}}" >> $GITHUB_ENV
            [ ! -z ${{ inputs.output }} ] && echo "output=-o ${{ inputs.output}}" >> $GITHUB_ENV || echo "output=-o dnsx.log" >> $GITHUB_ENV
            [ ! -z "${{ inputs.flags }}" ] && echo "flags=${{ inputs.flags }}" >> $GITHUB_ENV
            [ ! -z ${{ inputs.resolver }} ] && echo "resolver=-r ${{ inputs.resolver}}" >> $GITHUB_ENV
            ${{ inputs.json }} && echo "json=-json" >> $GITHUB_ENV
            echo "/home/runner/go/bin/" >> $GITHUB_PATH

      - name: dnsx_run
        run: |
            dnsx \
            ${{ env.list }} \
            ${{ env.output }} \
            ${{ env.json }} \
            ${{ env.resolver }} \
            ${{ env.flags }}
            
            
       
              
